[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "automate-mobile-applications"
version = "0.1.0"
dependencies = [
]

[project.optional-dependencies]
dev = [
    "mobile-game-ad-detection @ ./libs/mobile-game-ad-detection"
]